FROM apikit-dev:latest

# For APIKit CLI testing

# Implicit by base image
# WORKDIR /app
# COPY requirements-app.txt .
# RUN env/bin/pip install -r requirements-app.txt --no-cache-dir
# COPY ./apps* /app/apps

RUN apk add curl
